[package]
name = "petrel"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
diameter = "0.1"
log = "0.4"
env_logger = "0.9"
futures = "0.3"
chrono = "0.4"

